### PR TITLE
PGET Enhancements

### PR DESCRIPTION
**Pull request by tempusfrangit**
* Use `cobra.Command` and `viper` to handle CLI arguments *and* load from ENV where beneficial
* add `--resolve` argument
* add `--connect-timeout` argument

### CODE REVIEW

**Comment by tempusfrangit** [comment]
Still TODO: restructure pget into more logical functions (maybe even packages) for testing
Implement HTTP pipeline and multiplexing 

Maybe: Coalesce multiple invocations of pget into a single background downloader.

**Comment by tempusfrangit** [comment]
Still todo:

--manifest of many files to download (file or STDIN with `-` argument)

Consider: https://github.com/curl/curl/issues/5774 for pget downloading behavior.

implement tests.

**Comment by technillogue** [comment]
it might be nice to split this up into multiple PRs, one keep the exact same functionally but restructuring you want, and (an)other PR(s) for the functionality changes

**Comment by tempusfrangit** [comment]
Now that I have the code a bit more structured, I can split this into some separate PRs. Let me get the last bit in this thread completed [one more] and I'll consolidate:
* Current behavior + Cobra.Command + Viper
* New client code + new flags
* New backend code [next commit]
* Manifest support [Pending PR]

**Pull request closed without merging**
